// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreatOrderItem(ctx context.Context, arg CreatOrderItemParams) (OrderItem, error)
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	FindProductByID(ctx context.Context, id int64) (Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
